[options]
admin_passwd = $pbkdf2-sha512$600000$.j9HqBVCyLlX6t0bY6y1dg$XBtyIK57WECbBVc6gcWTth.j3x85UNhpzhe7JkKUEcJ4NtifL2k5CQmtiWAzfpYyzqEDl9hTEk.VDRLJvZHx3Q
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = D:/Projects/Odoo dev/versions/19.0/odoo-server/addons,D:/Projects/Odoo dev/versions/19.0/custom_addons
data_dir = D:/Projects/Odoo dev/versions/19.0/data
default_productivity_apps = True
http_interface = 127.0.0.1

; username/password is admin/admin
